### ISSUE TITLE
mouse rotation not active

### ISSUE THREAD

**Issue by edljk** [SimonDanisch/Makie.jl#16]
It happens quite frequently that it is not possible to rotate the scene with the mouse whereas zooming in or out is always possible. I am on linux with `GLFW  1.4.1  master` + `glfw-3.2.1`.
Sometime rotation woks perfectly on the same scene..
I do not know which experiments/information could help to identify the problem..

**Comment by SimonDanisch** [comment]
Yes, you need to close the window inbetween... Fixing this bug is next on my list

**Comment by SimonDanisch** [comment]
Fixed it: 48f3bf036b860b26e7e9a847b51d4c9d93c1b56e :)

**Comment by edljk** [comment]
Almost same subject: is it on purpose that mouse translation or zooming are not active after 2D plots?
e.g.
```julia
using Makie
scene = Scene(resolution = (500, 500))
scatter(rand(10), rand(10))
center!(scene)
```

**Comment by SimonDanisch** [comment]
You need to press ctrl ;) I'm working on the camera code right now - when done I will push some more documentation!

**Comment by edljk** [comment]
Oups, sorry for the noise! Thanks.
