### ISSUE TITLE
change light of a scene

### ISSUE THREAD

**Issue by edljk** [SimonDanisch/Makie.jl#20]
the key `:light` is not a `Node` which makes it static. Is it on purpose?

**Comment by SimonDanisch** [comment]
Fixed it... this also needs the newest master of GLAbstraction! Note, that right now I only respect the position of the light, so the other attributes are kinda meaningless right now. I really need to give the whole shading a bit of a revamp ;)

**Comment by edljk** [comment]
Works great! 
Btw, can an object be illuminated by more than one light?

**Comment by SimonDanisch** [comment]
Nope... I could include that option whenever I rework the shading...
