### ISSUE TITLE
update colors in mesh

### ISSUE THREAD

**Issue by edljk** [SimonDanisch/Makie.jl#21]
Exploring the huge possibilities of Makie, I was surprised that the following example didn't actualize the colors. Whereas the analogous call for meshscatter actualizes the color.
It is not the right way to update an attribute?

```julia
using Makie
scene = Scene(resolution = (500, 500))
x = [0, 1, 2, 0]
y = [0, 0, 1, 2]
z = [0, 2, 0, 1]
color = [:red, :green, :blue, :yellow]
i = [0, 0, 0, 1]
j = [1, 2, 3, 2]
k = [2, 3, 1, 3]
indices = [1, 2, 3, 1, 3, 4, 1, 4, 2, 2, 3, 4]
m = mesh(x, y, z, indices, color = color)
wireframe(m[:mesh], color = :black, linewidth = 2)
m[:color] = [:blue, :red, :blue, :red]
center!(scene)
```

**Comment by SimonDanisch** [comment]
likely a bug, thanks for testing!

**Comment by SimonDanisch** [comment]
Lol, bamboozled again by the horrible way I handle a mesh signals... should be fixed in GLAbstraction :)
