### ISSUE TITLE
`scene[:time]` doesn't update for 2nd scene

### ISSUE THREAD

**Issue by ssfrr** [SimonDanisch/Makie.jl#40]
MWE:

```julia
using Makie

scene = Scene()
t = linspace(0,4pi,100)
y = lift_node(scene[:time]) do phase
    cos.(t .+ phase*2pi+1)
end
lines(t, y)
center!(scene)
```

When you run this the 1st time you see a sinusoid moving across the screen. Running it again (e.g. from the REPL or Atom) the wave displays but doesn't move.

**Comment by SimonDanisch** [comment]
that was indeed a bug ;)
