### ISSUE TITLE
Unexpected position of 2D Axis ticks labels 

### ISSUE THREAD

**Issue by alblaz** [SimonDanisch/MakiE.jl#7]
The example scattermouse.jl give me a result which is different compare to the one showed in the README.
The position of the x and y axis ticks labels are respectively on the upper side and on the right side instead of being in the lower and the left side.
![test](https://user-images.githubusercontent.com/20283877/31878565-cdc27524-b7da-11e7-8ead-91bbe7c7a09c.png)

**Comment by SimonDanisch** [comment]
Should be fixed on master :)

**Comment by alblaz** [comment]
Great! :)
